app = 'ophtho'
primary_region = 'iad'


[image]
  ref = "janbol706/langflow-app:linux-amd64"

[http_service]
  internal_port = 7860
#  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[mounts]]
  source = "data_volume"
  destination = "/app/OG_Training_Books"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
